version: '3'
services:
  django-admin:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: django-admin
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/opt/app/static/
    networks:
      - my_net2
    command: >
      bash -c "python manage.py migrate && python manage.py create_superuser && python manage.py runserver 0.0.0.0:8000  && uwsgi --strict --ini uwsgi/uwsgi.ini"

volumes:
  static_volume:

networks:
  my_net2:
    external: true
